# Generated by Django 4.2.1 on 2023-05-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lbms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price_fee',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
